/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ParcelId = IDL.Nat;
export const ParcelStatus = IDL.Variant({
  'pending' : IDL.Null,
  'inTransit' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Parcel = IDL.Record({
  'id' : ParcelId,
  'status' : ParcelStatus,
  'additionalInfo' : IDL.Text,
  'trackingCode' : IDL.Text,
  'clientName' : IDL.Text,
  'owner' : IDL.Principal,
  'destinationAddress' : IDL.Text,
  'createdAt' : IDL.Int,
  'parcelType' : IDL.Text,
  'updatedAt' : IDL.Int,
  'clientPhone' : IDL.Text,
  'senderName' : IDL.Text,
  'parcelCount' : IDL.Nat,
});
export const TransporterStatus = IDL.Variant({
  'pending' : IDL.Null,
  'validated' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const TransporterProfile = IDL.Record({
  'status' : TransporterStatus,
  'principal' : IDL.Principal,
  'rejectedAt' : IDL.Opt(Timestamp),
  'validatedAt' : IDL.Opt(Timestamp),
  'registeredAt' : Timestamp,
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const NewsLinkInput = IDL.Record({
  'url' : IDL.Text,
  'linkLabel' : IDL.Text,
});
export const NewsLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'linkLabel' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DashboardStats = IDL.Record({
  'pendingCount' : IDL.Nat,
  'byTransporteur' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
  'inTransitCount' : IDL.Nat,
  'totalParcels' : IDL.Nat,
  'deliveredCount' : IDL.Nat,
});
export const NewsPage = IDL.Record({
  'title' : IDL.Text,
  'whatsappLink' : IDL.Text,
  'description' : IDL.Text,
  'links' : IDL.Vec(NewsLink),
});
export const ParcelInput = IDL.Record({
  'additionalInfo' : IDL.Text,
  'trackingCode' : IDL.Text,
  'clientName' : IDL.Text,
  'destinationAddress' : IDL.Text,
  'parcelType' : IDL.Text,
  'clientPhone' : IDL.Text,
  'senderName' : IDL.Text,
  'parcelCount' : IDL.Nat,
});
export const ParcelFilter = IDL.Record({
  'status' : IDL.Opt(ParcelStatus),
  'toDate' : IDL.Opt(IDL.Int),
  'fromDate' : IDL.Opt(IDL.Int),
  'clientNameQuery' : IDL.Opt(IDL.Text),
});
export const ParcelUpdate = IDL.Record({
  'status' : IDL.Opt(ParcelStatus),
  'additionalInfo' : IDL.Opt(IDL.Text),
  'trackingCode' : IDL.Opt(IDL.Text),
  'clientName' : IDL.Opt(IDL.Text),
  'destinationAddress' : IDL.Opt(IDL.Text),
  'parcelType' : IDL.Opt(IDL.Text),
  'clientPhone' : IDL.Opt(IDL.Text),
  'senderName' : IDL.Opt(IDL.Text),
  'parcelCount' : IDL.Opt(IDL.Nat),
});
export const NewsPageInput = IDL.Record({
  'title' : IDL.Text,
  'whatsappLink' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__newsState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__parcelNextId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__parcels' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Parcel)],
      ['query'],
    ),
  '__transporters' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, TransporterProfile))],
      ['query'],
    ),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addNewsLink' : IDL.Func([NewsLinkInput], [NewsLink], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnyParcel' : IDL.Func([ParcelId], [IDL.Opt(Parcel)], []),
  'deleteMyParcel' : IDL.Func([ParcelId], [IDL.Opt(Parcel)], []),
  'deleteNewsLink' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMyParcel' : IDL.Func([ParcelId], [IDL.Opt(Parcel)], ['query']),
  'getMyTransporterProfile' : IDL.Func(
      [],
      [IDL.Opt(TransporterProfile)],
      ['query'],
    ),
  'getNewsPage' : IDL.Func([], [NewsPage], ['query']),
  'getTransporterProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TransporterProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerTransporterValidated' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
  'listMyParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
  'listTransporters' : IDL.Func([], [IDL.Vec(TransporterProfile)], ['query']),
  'listTransportersByStatus' : IDL.Func(
      [TransporterStatus],
      [IDL.Vec(TransporterProfile)],
      ['query'],
    ),
  'registerAsTransporter' : IDL.Func([], [TransporterProfile], []),
  'registerParcel' : IDL.Func([ParcelInput], [ParcelId], []),
  'rejectTransporter' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TransporterProfile)],
      [],
    ),
  'revokeTransporter' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TransporterProfile)],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchParcels' : IDL.Func([ParcelFilter], [IDL.Vec(Parcel)], ['query']),
  'updateAnyParcel' : IDL.Func([ParcelId, ParcelUpdate], [IDL.Opt(Parcel)], []),
  'updateMyParcel' : IDL.Func([ParcelId, ParcelUpdate], [IDL.Opt(Parcel)], []),
  'updateNewsLink' : IDL.Func(
      [IDL.Nat, NewsLinkInput],
      [IDL.Opt(NewsLink)],
      [],
    ),
  'updateNewsPage' : IDL.Func([NewsPageInput], [], []),
  'validateTransporter' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TransporterProfile)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ParcelId = IDL.Nat;
  const ParcelStatus = IDL.Variant({
    'pending' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Parcel = IDL.Record({
    'id' : ParcelId,
    'status' : ParcelStatus,
    'additionalInfo' : IDL.Text,
    'trackingCode' : IDL.Text,
    'clientName' : IDL.Text,
    'owner' : IDL.Principal,
    'destinationAddress' : IDL.Text,
    'createdAt' : IDL.Int,
    'parcelType' : IDL.Text,
    'updatedAt' : IDL.Int,
    'clientPhone' : IDL.Text,
    'senderName' : IDL.Text,
    'parcelCount' : IDL.Nat,
  });
  const TransporterStatus = IDL.Variant({
    'pending' : IDL.Null,
    'validated' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const TransporterProfile = IDL.Record({
    'status' : TransporterStatus,
    'principal' : IDL.Principal,
    'rejectedAt' : IDL.Opt(Timestamp),
    'validatedAt' : IDL.Opt(Timestamp),
    'registeredAt' : Timestamp,
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const NewsLinkInput = IDL.Record({
    'url' : IDL.Text,
    'linkLabel' : IDL.Text,
  });
  const NewsLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'linkLabel' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DashboardStats = IDL.Record({
    'pendingCount' : IDL.Nat,
    'byTransporteur' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
    'inTransitCount' : IDL.Nat,
    'totalParcels' : IDL.Nat,
    'deliveredCount' : IDL.Nat,
  });
  const NewsPage = IDL.Record({
    'title' : IDL.Text,
    'whatsappLink' : IDL.Text,
    'description' : IDL.Text,
    'links' : IDL.Vec(NewsLink),
  });
  const ParcelInput = IDL.Record({
    'additionalInfo' : IDL.Text,
    'trackingCode' : IDL.Text,
    'clientName' : IDL.Text,
    'destinationAddress' : IDL.Text,
    'parcelType' : IDL.Text,
    'clientPhone' : IDL.Text,
    'senderName' : IDL.Text,
    'parcelCount' : IDL.Nat,
  });
  const ParcelFilter = IDL.Record({
    'status' : IDL.Opt(ParcelStatus),
    'toDate' : IDL.Opt(IDL.Int),
    'fromDate' : IDL.Opt(IDL.Int),
    'clientNameQuery' : IDL.Opt(IDL.Text),
  });
  const ParcelUpdate = IDL.Record({
    'status' : IDL.Opt(ParcelStatus),
    'additionalInfo' : IDL.Opt(IDL.Text),
    'trackingCode' : IDL.Opt(IDL.Text),
    'clientName' : IDL.Opt(IDL.Text),
    'destinationAddress' : IDL.Opt(IDL.Text),
    'parcelType' : IDL.Opt(IDL.Text),
    'clientPhone' : IDL.Opt(IDL.Text),
    'senderName' : IDL.Opt(IDL.Text),
    'parcelCount' : IDL.Opt(IDL.Nat),
  });
  const NewsPageInput = IDL.Record({
    'title' : IDL.Text,
    'whatsappLink' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__newsState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__parcelNextId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__parcels' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Parcel)],
        ['query'],
      ),
    '__transporters' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, TransporterProfile))],
        ['query'],
      ),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addNewsLink' : IDL.Func([NewsLinkInput], [NewsLink], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnyParcel' : IDL.Func([ParcelId], [IDL.Opt(Parcel)], []),
    'deleteMyParcel' : IDL.Func([ParcelId], [IDL.Opt(Parcel)], []),
    'deleteNewsLink' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMyParcel' : IDL.Func([ParcelId], [IDL.Opt(Parcel)], ['query']),
    'getMyTransporterProfile' : IDL.Func(
        [],
        [IDL.Opt(TransporterProfile)],
        ['query'],
      ),
    'getNewsPage' : IDL.Func([], [NewsPage], ['query']),
    'getTransporterProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TransporterProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerTransporterValidated' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
    'listMyParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
    'listTransporters' : IDL.Func([], [IDL.Vec(TransporterProfile)], ['query']),
    'listTransportersByStatus' : IDL.Func(
        [TransporterStatus],
        [IDL.Vec(TransporterProfile)],
        ['query'],
      ),
    'registerAsTransporter' : IDL.Func([], [TransporterProfile], []),
    'registerParcel' : IDL.Func([ParcelInput], [ParcelId], []),
    'rejectTransporter' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TransporterProfile)],
        [],
      ),
    'revokeTransporter' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TransporterProfile)],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchParcels' : IDL.Func([ParcelFilter], [IDL.Vec(Parcel)], ['query']),
    'updateAnyParcel' : IDL.Func(
        [ParcelId, ParcelUpdate],
        [IDL.Opt(Parcel)],
        [],
      ),
    'updateMyParcel' : IDL.Func(
        [ParcelId, ParcelUpdate],
        [IDL.Opt(Parcel)],
        [],
      ),
    'updateNewsLink' : IDL.Func(
        [IDL.Nat, NewsLinkInput],
        [IDL.Opt(NewsLink)],
        [],
      ),
    'updateNewsPage' : IDL.Func([NewsPageInput], [], []),
    'validateTransporter' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TransporterProfile)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };