/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface DashboardStats {
  'pendingCount' : bigint,
  'byTransporteur' : Array<[Principal, bigint]>,
  'inTransitCount' : bigint,
  'totalParcels' : bigint,
  'deliveredCount' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface NewsLink {
  'id' : bigint,
  'url' : string,
  'linkLabel' : string,
}
export interface NewsLinkInput { 'url' : string, 'linkLabel' : string }
export interface NewsPage {
  'title' : string,
  'whatsappLink' : string,
  'description' : string,
  'links' : Array<NewsLink>,
}
export interface NewsPageInput {
  'title' : string,
  'whatsappLink' : string,
  'description' : string,
}
export interface Parcel {
  'id' : ParcelId,
  'status' : ParcelStatus,
  'additionalInfo' : string,
  'trackingCode' : string,
  'clientName' : string,
  'owner' : Principal,
  'destinationAddress' : string,
  'createdAt' : bigint,
  'parcelType' : string,
  'updatedAt' : bigint,
  'clientPhone' : string,
  'senderName' : string,
  'parcelCount' : bigint,
}
export interface ParcelFilter {
  'status' : [] | [ParcelStatus],
  'toDate' : [] | [bigint],
  'fromDate' : [] | [bigint],
  'clientNameQuery' : [] | [string],
}
export type ParcelId = bigint;
export interface ParcelInput {
  'additionalInfo' : string,
  'trackingCode' : string,
  'clientName' : string,
  'destinationAddress' : string,
  'parcelType' : string,
  'clientPhone' : string,
  'senderName' : string,
  'parcelCount' : bigint,
}
export type ParcelStatus = { 'pending' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null };
export interface ParcelUpdate {
  'status' : [] | [ParcelStatus],
  'additionalInfo' : [] | [string],
  'trackingCode' : [] | [string],
  'clientName' : [] | [string],
  'destinationAddress' : [] | [string],
  'parcelType' : [] | [string],
  'clientPhone' : [] | [string],
  'senderName' : [] | [string],
  'parcelCount' : [] | [bigint],
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export interface TransporterProfile {
  'status' : TransporterStatus,
  'principal' : Principal,
  'rejectedAt' : [] | [Timestamp],
  'validatedAt' : [] | [Timestamp],
  'registeredAt' : Timestamp,
}
export type TransporterStatus = { 'pending' : null } |
  { 'validated' : null } |
  { 'rejected' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__newsState' : ActorMethod<[], any>,
  '__parcelNextId' : ActorMethod<[], any>,
  '__parcels' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Parcel>>,
  '__transporters' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, TransporterProfile]>
  >,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addNewsLink' : ActorMethod<[NewsLinkInput], NewsLink>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAnyParcel' : ActorMethod<[ParcelId], [] | [Parcel]>,
  'deleteMyParcel' : ActorMethod<[ParcelId], [] | [Parcel]>,
  'deleteNewsLink' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyParcel' : ActorMethod<[ParcelId], [] | [Parcel]>,
  'getMyTransporterProfile' : ActorMethod<[], [] | [TransporterProfile]>,
  'getNewsPage' : ActorMethod<[], NewsPage>,
  'getTransporterProfile' : ActorMethod<[Principal], [] | [TransporterProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerTransporterValidated' : ActorMethod<[], boolean>,
  'listAllParcels' : ActorMethod<[], Array<Parcel>>,
  'listMyParcels' : ActorMethod<[], Array<Parcel>>,
  'listTransporters' : ActorMethod<[], Array<TransporterProfile>>,
  'listTransportersByStatus' : ActorMethod<
    [TransporterStatus],
    Array<TransporterProfile>
  >,
  'registerAsTransporter' : ActorMethod<[], TransporterProfile>,
  'registerParcel' : ActorMethod<[ParcelInput], ParcelId>,
  'rejectTransporter' : ActorMethod<[Principal], [] | [TransporterProfile]>,
  'revokeTransporter' : ActorMethod<[Principal], [] | [TransporterProfile]>,
  'schema' : ActorMethod<[], string>,
  'searchParcels' : ActorMethod<[ParcelFilter], Array<Parcel>>,
  'updateAnyParcel' : ActorMethod<[ParcelId, ParcelUpdate], [] | [Parcel]>,
  'updateMyParcel' : ActorMethod<[ParcelId, ParcelUpdate], [] | [Parcel]>,
  'updateNewsLink' : ActorMethod<[bigint, NewsLinkInput], [] | [NewsLink]>,
  'updateNewsPage' : ActorMethod<[NewsPageInput], undefined>,
  'validateTransporter' : ActorMethod<[Principal], [] | [TransporterProfile]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];