/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Timestamp = bigint;
export interface ParcelFilter {
    status?: ParcelStatus;
    toDate?: bigint;
    fromDate?: bigint;
    clientNameQuery?: string;
}
export interface NewsLink {
    id: bigint;
    url: string;
    linkLabel: string;
}
export interface NewsPageInput {
    title: string;
    whatsappLink: string;
    description: string;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type ParcelId = bigint;
export interface ParcelInput {
    additionalInfo: string;
    trackingCode: string;
    clientName: string;
    destinationAddress: string;
    parcelType: string;
    clientPhone: string;
    senderName: string;
    parcelCount: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface DashboardStats {
    pendingCount: bigint;
    byTransporteur: Array<[Principal, bigint]>;
    inTransitCount: bigint;
    totalParcels: bigint;
    deliveredCount: bigint;
}
export interface TransporterProfile {
    status: TransporterStatus;
    principal: Principal;
    rejectedAt?: Timestamp;
    validatedAt?: Timestamp;
    registeredAt: Timestamp;
}
export interface ParcelUpdate {
    status?: ParcelStatus;
    additionalInfo?: string;
    trackingCode?: string;
    clientName?: string;
    destinationAddress?: string;
    parcelType?: string;
    clientPhone?: string;
    senderName?: string;
    parcelCount?: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface NewsPage {
    title: string;
    whatsappLink: string;
    description: string;
    links: Array<NewsLink>;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface Parcel {
    id: ParcelId;
    status: ParcelStatus;
    additionalInfo: string;
    trackingCode: string;
    clientName: string;
    owner: Principal;
    destinationAddress: string;
    createdAt: bigint;
    parcelType: string;
    updatedAt: bigint;
    clientPhone: string;
    senderName: string;
    parcelCount: bigint;
}
export interface NewsLinkInput {
    url: string;
    linkLabel: string;
}
export enum ParcelStatus {
    pending = "pending",
    inTransit = "inTransit",
    delivered = "delivered"
}
export enum TransporterStatus {
    pending = "pending",
    validated = "validated",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __newsState(): Promise<any>;
    __parcelNextId(): Promise<any>;
    __parcels(io: bigint | null, count: bigint | null): Promise<Array<Parcel>>;
    __transporters(ko: Principal | null, count: bigint | null): Promise<Array<[Principal, TransporterProfile]>>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addNewsLink(input: NewsLinkInput): Promise<NewsLink>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAnyParcel(id: ParcelId): Promise<Parcel | null>;
    deleteMyParcel(id: ParcelId): Promise<Parcel | null>;
    deleteNewsLink(id: bigint): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getMyParcel(id: ParcelId): Promise<Parcel | null>;
    getMyTransporterProfile(): Promise<TransporterProfile | null>;
    getNewsPage(): Promise<NewsPage>;
    getTransporterProfile(principal: Principal): Promise<TransporterProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerTransporterValidated(): Promise<boolean>;
    listAllParcels(): Promise<Array<Parcel>>;
    listMyParcels(): Promise<Array<Parcel>>;
    listTransporters(): Promise<Array<TransporterProfile>>;
    listTransportersByStatus(status: TransporterStatus): Promise<Array<TransporterProfile>>;
    registerAsTransporter(): Promise<TransporterProfile>;
    registerParcel(input: ParcelInput): Promise<ParcelId>;
    rejectTransporter(principal: Principal): Promise<TransporterProfile | null>;
    revokeTransporter(principal: Principal): Promise<TransporterProfile | null>;
    schema(): Promise<string>;
    searchParcels(filter: ParcelFilter): Promise<Array<Parcel>>;
    updateAnyParcel(id: ParcelId, update: ParcelUpdate): Promise<Parcel | null>;
    updateMyParcel(id: ParcelId, update: ParcelUpdate): Promise<Parcel | null>;
    updateNewsLink(id: bigint, input: NewsLinkInput): Promise<NewsLink | null>;
    updateNewsPage(input: NewsPageInput): Promise<void>;
    validateTransporter(principal: Principal): Promise<TransporterProfile | null>;
}
import type { Cell as _Cell, Error as _Error, NewsLink as _NewsLink, Parcel as _Parcel, ParcelFilter as _ParcelFilter, ParcelId as _ParcelId, ParcelStatus as _ParcelStatus, ParcelUpdate as _ParcelUpdate, Result as _Result, Result__1 as _Result__1, Timestamp as _Timestamp, TransporterProfile as _TransporterProfile, TransporterStatus as _TransporterStatus, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __newsState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__newsState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__newsState();
            return result;
        }
    }
    async __parcelNextId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__parcelNextId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__parcelNextId();
            return result;
        }
    }
    async __parcels(arg0: bigint | null, arg1: bigint | null): Promise<Array<Parcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.__parcels(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__parcels(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __transporters(arg0: Principal | null, arg1: bigint | null): Promise<Array<[Principal, TransporterProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__transporters(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__transporters(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addNewsLink(arg0: NewsLinkInput): Promise<NewsLink> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsLink(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAnyParcel(arg0: ParcelId): Promise<Parcel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnyParcel(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnyParcel(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMyParcel(arg0: ParcelId): Promise<Parcel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMyParcel(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMyParcel(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNewsLink(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNewsLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNewsLink(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMyParcel(arg0: ParcelId): Promise<Parcel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyParcel(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyParcel(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransporterProfile(): Promise<TransporterProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransporterProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransporterProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsPage(): Promise<NewsPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsPage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsPage();
            return result;
        }
    }
    async getTransporterProfile(arg0: Principal): Promise<TransporterProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransporterProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransporterProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerTransporterValidated(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerTransporterValidated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerTransporterValidated();
            return result;
        }
    }
    async listAllParcels(): Promise<Array<Parcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllParcels();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllParcels();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyParcels(): Promise<Array<Parcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyParcels();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyParcels();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTransporters(): Promise<Array<TransporterProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransporters();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransporters();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTransportersByStatus(arg0: TransporterStatus): Promise<Array<TransporterProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransportersByStatus(to_candid_TransporterStatus_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransportersByStatus(to_candid_TransporterStatus_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAsTransporter(): Promise<TransporterProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsTransporter();
                return from_candid_TransporterProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsTransporter();
            return from_candid_TransporterProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerParcel(arg0: ParcelInput): Promise<ParcelId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerParcel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerParcel(arg0);
            return result;
        }
    }
    async rejectTransporter(arg0: Principal): Promise<TransporterProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTransporter(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTransporter(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async revokeTransporter(arg0: Principal): Promise<TransporterProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeTransporter(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeTransporter(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchParcels(arg0: ParcelFilter): Promise<Array<Parcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchParcels(to_candid_ParcelFilter_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchParcels(to_candid_ParcelFilter_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAnyParcel(arg0: ParcelId, arg1: ParcelUpdate): Promise<Parcel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnyParcel(arg0, to_candid_ParcelUpdate_n40(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnyParcel(arg0, to_candid_ParcelUpdate_n40(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyParcel(arg0: ParcelId, arg1: ParcelUpdate): Promise<Parcel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyParcel(arg0, to_candid_ParcelUpdate_n40(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyParcel(arg0, to_candid_ParcelUpdate_n40(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNewsLink(arg0: bigint, arg1: NewsLinkInput): Promise<NewsLink | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsLink(arg0, arg1);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsLink(arg0, arg1);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNewsPage(arg0: NewsPageInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsPage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsPage(arg0);
            return result;
        }
    }
    async validateTransporter(arg0: Principal): Promise<TransporterProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateTransporter(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateTransporter(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cell_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ParcelStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParcelStatus): ParcelStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Parcel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Parcel): Parcel {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TransporterProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransporterProfile): TransporterProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TransporterStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransporterStatus): TransporterStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Parcel]): Parcel | null {
    return value.length === 0 ? null : from_candid_Parcel_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransporterProfile]): TransporterProfile | null {
    return value.length === 0 ? null : from_candid_TransporterProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsLink]): NewsLink | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TransporterStatus;
    principal: Principal;
    rejectedAt: [] | [_Timestamp];
    validatedAt: [] | [_Timestamp];
    registeredAt: _Timestamp;
}): {
    status: TransporterStatus;
    principal: Principal;
    rejectedAt?: Timestamp;
    validatedAt?: Timestamp;
    registeredAt: Timestamp;
} {
    return {
        status: from_candid_TransporterStatus_n12(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        rejectedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.rejectedAt)),
        validatedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.validatedAt)),
        registeredAt: value.registeredAt
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n24(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n28(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ParcelId;
    status: _ParcelStatus;
    additionalInfo: string;
    trackingCode: string;
    clientName: string;
    owner: Principal;
    destinationAddress: string;
    createdAt: bigint;
    parcelType: string;
    updatedAt: bigint;
    clientPhone: string;
    senderName: string;
    parcelCount: bigint;
}): {
    id: ParcelId;
    status: ParcelStatus;
    additionalInfo: string;
    trackingCode: string;
    clientName: string;
    owner: Principal;
    destinationAddress: string;
    createdAt: bigint;
    parcelType: string;
    updatedAt: bigint;
    clientPhone: string;
    senderName: string;
    parcelCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ParcelStatus_n5(_uploadFile, _downloadFile, value.status),
        additionalInfo: value.additionalInfo,
        trackingCode: value.trackingCode,
        clientName: value.clientName,
        owner: value.owner,
        destinationAddress: value.destinationAddress,
        createdAt: value.createdAt,
        parcelType: value.parcelType,
        updatedAt: value.updatedAt,
        clientPhone: value.clientPhone,
        senderName: value.senderName,
        parcelCount: value.parcelCount
    };
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _TransporterProfile]): [Principal, TransporterProfile] {
    return [
        value[0],
        from_candid_TransporterProfile_n10(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    validated: null;
} | {
    rejected: null;
}): TransporterStatus {
    return "pending" in value ? TransporterStatus.pending : "validated" in value ? TransporterStatus.validated : "rejected" in value ? TransporterStatus.rejected : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n17(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    inTransit: null;
} | {
    delivered: null;
}): ParcelStatus {
    return "pending" in value ? ParcelStatus.pending : "inTransit" in value ? ParcelStatus.inTransit : "delivered" in value ? ParcelStatus.delivered : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Parcel>): Array<Parcel> {
    return value.map((x)=>from_candid_Parcel_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransporterProfile>): Array<TransporterProfile> {
    return value.map((x)=>from_candid_TransporterProfile_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _TransporterProfile]>): Array<[Principal, TransporterProfile]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ParcelFilter_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParcelFilter): _ParcelFilter {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_ParcelStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParcelStatus): _ParcelStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_ParcelUpdate_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParcelUpdate): _ParcelUpdate {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_TransporterStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransporterStatus): _TransporterStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: ParcelStatus;
    toDate?: bigint;
    fromDate?: bigint;
    clientNameQuery?: string;
}): {
    status: [] | [_ParcelStatus];
    toDate: [] | [bigint];
    fromDate: [] | [bigint];
    clientNameQuery: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_ParcelStatus_n38(_uploadFile, _downloadFile, value.status)) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        clientNameQuery: value.clientNameQuery ? candid_some(value.clientNameQuery) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: ParcelStatus;
    additionalInfo?: string;
    trackingCode?: string;
    clientName?: string;
    destinationAddress?: string;
    parcelType?: string;
    clientPhone?: string;
    senderName?: string;
    parcelCount?: bigint;
}): {
    status: [] | [_ParcelStatus];
    additionalInfo: [] | [string];
    trackingCode: [] | [string];
    clientName: [] | [string];
    destinationAddress: [] | [string];
    parcelType: [] | [string];
    clientPhone: [] | [string];
    senderName: [] | [string];
    parcelCount: [] | [bigint];
} {
    return {
        status: value.status ? candid_some(to_candid_ParcelStatus_n38(_uploadFile, _downloadFile, value.status)) : candid_none(),
        additionalInfo: value.additionalInfo ? candid_some(value.additionalInfo) : candid_none(),
        trackingCode: value.trackingCode ? candid_some(value.trackingCode) : candid_none(),
        clientName: value.clientName ? candid_some(value.clientName) : candid_none(),
        destinationAddress: value.destinationAddress ? candid_some(value.destinationAddress) : candid_none(),
        parcelType: value.parcelType ? candid_some(value.parcelType) : candid_none(),
        clientPhone: value.clientPhone ? candid_some(value.clientPhone) : candid_none(),
        senderName: value.senderName ? candid_some(value.senderName) : candid_none(),
        parcelCount: value.parcelCount ? candid_some(value.parcelCount) : candid_none()
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransporterStatus): {
    pending: null;
} | {
    validated: null;
} | {
    rejected: null;
} {
    return value == TransporterStatus.pending ? {
        pending: null
    } : value == TransporterStatus.validated ? {
        validated: null
    } : value == TransporterStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParcelStatus): {
    pending: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} {
    return value == ParcelStatus.pending ? {
        pending: null
    } : value == ParcelStatus.inTransit ? {
        inTransit: null
    } : value == ParcelStatus.delivered ? {
        delivered: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
